import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import WalletProvider from '../context/WalletProvider';
import { ethers } from 'ethers';
import {} from 'web3modal';
import { defaultWagmiConfig } from '@web3modal/wagmi/react/config'
import Link from 'next/link';
import { WagmiProvider, cookieStorage, createStorage } from 'wagmi'
import { mainnet, sepolia } from 'wagmi/chains'
import { createWeb3Modal } from '@web3modal/wagmi';
import { PayButton } from '../components/PayButton';
import { Query, QueryClient, QueryClientProvider } from '@tanstack/react-query';
import {config5} from '../config/wagmi';
export const projectId = '58285468e8924fcbb4590fa95967cbd9';
import { injected } from '@wagmi/connectors'
import {http, createConfig} from '@wagmi/core'
import Header from '../components/Header';
import { createContext, useContext, useState } from 'react';

if (!projectId) throw new Error('Project ID is not defined')

const metadata = {
  name: 'Web3Modal',
  description: 'Web3Modal Example',
  url: 'http://localhost:3000/',
  icons: ['https://avatars.githubusercontent.com/u/37784886']
}
let counter:number = 0;


const chains = [ mainnet,sepolia] as const
export const config1 = defaultWagmiConfig({
  chains,
  projectId,
  metadata,
  ssr: true,
  connectors: [injected()],
    transports: {
        [mainnet.id]: http(),
    },
  storage: createStorage({
    storage: cookieStorage
  }),
});
const queryClient = new QueryClient()
createWeb3Modal({wagmiConfig: config1, projectId});
const Home: NextPage = () => {
  const WalletContext = createContext(null);
  return (
    <div> <Header/>
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

  
      <main className={styles.main}>
        <ConnectButton />
        <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{' '}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>
        aaaaaaaaaaaaa
        <WagmiProvider config={config5}>

    </WagmiProvider>

    <WagmiProvider config={config1}>
<w3m-button />
<QueryClientProvider client={queryClient}>
    <PayButton price={5}/>
    </QueryClientProvider>
</WagmiProvider>
        <Link href={{ pathname: '/about', query: { message: 'hello' } }}>About</Link>
      </main>

    </div>
    </div>
  );
};

export default Home;
